#ifndef CONTRACTERROR_H
#define CONTRACTERROR_H

enum TokenErrorType
{
    TOKENOK =0,
    TOKENFORMATERROR = 1,
    TOKENFLAGSIZEERROR = 2,
    TOKENWITNESSSIZEEROR = 3,
    TOKENINPUTSIZEERROR = 4,
    TOKENOUTPUTSIZEERROR = 5,
    TOKENTXNOFIND = 6,
    TOKENWITNESSERROR = 7,
    TOKENINPUTERROR = 8 ,
    TOKENOUTPUTERROR = 9,
    TOKENSTATISTICS = 10
};



#endif // CONTRACTERROR_H
